ruff/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.contrib.auth.views import login


admin.autodiscover()
app_name = 'ruff'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^news/$', views.news, name='news'),
    url(r'^location_stored/$', views.location_stored, name='location_stored'),
    url(r'^about/$', views.about, name='about'),
    url(r'^event/$', views.event, name='event'),
    url(r'^event/date_filter/$', views.event_date_filter, name='event_date_filter'),
    url(r'^event/filter/$', views.event_filter, name='event_filter'),
    url(r'^event/view/(?P<event_id>[0-9]+)/$', views.view_single_event, name='view_single_event'),
    url(r'^ruffadmin/$', views.event_details, name='event_details'),
    url(r'^ruffadmin/event_details/$', views.event_details, name='event_details'),
    url(r'^ruffadmin/event_form/$', views.event_form, name='event_form'),
    url(r'^ruffadmin/event/delete/(?P<event_id>[0-9]+)/$', views.delete_event_detail, name='delete_event'),
    url(r'^ruffadmin/event/update/(?P<event_id>[0-9]+)/$', views.update_event_detail, name='update_event'),
    url(r'^ruffadmin/event/view/(?P<event_id>[0-9]+)/$', views.view_event_detail, name='view_event'),
    url(r'^hike/$', views.hike, name='hike'),
    url(r'^hike/location/$', views.hike_location, name='hike_location'),
    url(r'^hike/view/(?P<hike_id>[0-9]+)/$', views.view_single_hike, name='view_single_hike'),
    url(r'^hike/distance_filter/$', views.hike_distance, name='hike_distance'),
    url(r'^hike_review_form/(?P<hike_id>[0-9]+)/$', views.hike_review_form, name='hike_review_form'),
    url(r'^ruffadmin/hike_details/$', views.hike_details, name='hike_details'),
    url(r'^ruffadmin/hike_form/$', views.hike_form, name='hike_form'),
    url(r'^ruffadmin/hike/delete/(?P<hike_id>[0-9]+)/$', views.delete_hike_detail, name='delete_hike'),
    url(r'^ruffadmin/hike/review/delete/(?P<hike_id>[0-9]+)/(?P<review_id>[0-9]+)/$',
        views.delete_hike_review, name='delete_hike_review'),
    url(r'^ruffadmin/hike/update/(?P<hike_id>[0-9]+)/$', views.update_hike_detail, name='update_hike'),
    url(r'^ruffadmin/hike/view/(?P<hike_id>[0-9]+)/$', views.view_hike_detail, name='view_hike'),
    url(r'^park/$', views.park, name='park'),
    url(r'^park/location/$', views.park_location, name='park_location'),
    url(r'^park/view/(?P<park_id>[0-9]+)/$', views.view_single_park, name='view_single_park'),
    url(r'^park/distance_filter/$', views.park_distance, name='park_distance'),
    url(r'^park_review_form/(?P<park_id>[0-9]+)/$', views.park_review_form, name='park_review_form'),
    url(r'^ruffadmin/park_details/$', views.park_details, name='park_details'),
    url(r'^ruffadmin/park_form/$', views.park_form, name='park_form'),
    url(r'^ruffadmin/park/delete/(?P<park_id>[0-9]+)/$', views.delete_park_detail, name='delete_park'),
    url(r'^ruffadmin/park/review/delete/(?P<park_id>[0-9]+)/(?P<review_id>[0-9]+)/$',
        views.delete_park_review, name='delete_park_review'),
    url(r'^ruffadmin/park/update/(?P<park_id>[0-9]+)/$', views.update_park_detail, name='update_park'),
    url(r'^ruffadmin/park/view/(?P<park_id>[0-9]+)/$', views.view_park_detail, name='view_park'),
    url(r'^restaurant/$', views.restaurant, name='restaurant'),
    url(r'^restaurant/location/$', views.restaurant_location, name='restaurant_location'),
    url(r'^restaurant/distance_filter/$', views.restaurant_distance, name='restaurant_distance'),
    url(r'^restaurant/view/(?P<restaurant_id>[0-9]+)/$', views.view_single_restaurant, name='view_single_restaurant'),
    url(r'^restaurant_review_form/(?P<restaurant_id>[0-9]+)/$', views.restaurant_review_form,
        name='restaurant_review_form'),
    url(r'^ruffadmin/restaurant_details/$', views.restaurant_details, name='restaurant_details'),
    url(r'^ruffadmin/restaurant_form/$', views.restaurant_form, name='restaurant_form'),
    url(r'^ruffadmin/restaurant/delete/(?P<restaurant_id>[0-9]+)/$', views.delete_restaurant_detail,
        name='delete_restaurant'),
    url(r'^ruffadmin/restaurant/review/delete/(?P<restaurant_id>[0-9]+)/(?P<review_id>[0-9]+)/$',
        views.delete_restaurant_review, name='delete_restaurant_review'),
    url(r'^ruffadmin/restaurant/update/(?P<restaurant_id>[0-9]+)/$', views.update_restaurant_detail,
        name='update_restaurant'),
    url(r'^ruffadmin/restaurant/view/(?P<restaurant_id>[0-9]+)/$', views.view_restaurant_detail,
        name='view_restaurant'),
    url(r'^login/$', login, {'template_name': 'admin/login.html'}),
]

ruffguide/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', admin.site.urls),
    url(r'^', include('ruff.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler400 = 'ruff.views.handler400'
handler403 = 'ruff.views.handler403'
handler404 = 'ruff.views.handler404'
handler500 = 'ruff.views.handler500'

ruff/forms.py
from django import forms


class EventsForm(forms.Form):
    type = forms.CharField(max_length=50)
    description = forms.TextInput()
    organiser = forms.CharField(max_length=100)
    cost = forms.TextInput()
    contact = forms.CharField(max_length=200)
    website = forms.URLField()
    location = forms.CharField(max_length=200)
    start_date = forms.CharField(max_length=15)
    end_date = forms.CharField(max_length=15)
    start_time = forms.CharField(max_length=10)
    end_time = forms.CharField(max_length=10)

class HikesForm(forms.Form):
    name = forms.CharField(max_length=50)
    location = forms.TextInput()
    distance = forms.FloatField()
    description = forms.TextInput()
    coordinates = forms.TextInput()
    difficulty = forms.CharField(max_length=200)
    more_info_link = forms.CharField(max_length=100, required=False)
    days_of_week = forms.TextInput()

class RestaurantsForm(forms.Form):
    name = forms.CharField(max_length=50)
    type = forms.TextInput()
    building_name = forms.TextInput()
    street_number = forms.IntegerField()
    street_name = forms.CharField(max_length=50)
    suburb = forms.CharField(max_length=50)
    postcode = forms.CharField(max_length=50)
    state = forms.CharField(max_length=50)
    phone_number = forms.CharField(max_length=50)
    description = forms.TextInput()
    days_of_week = forms.TextInput()

class ParksForm(forms.Form):
    name = forms.CharField(max_length=50)
    location = forms.TextInput()
    description = forms.TextInput()
    days_of_week = forms.TextInput()

class Restaurant_Review_Form(forms.Form):
    user = forms.CharField(max_length=50)
    rating = forms.TextInput()
    comments = forms.TextInput()

class Park_Review_Form(forms.Form):
    user = forms.CharField(max_length=50)
    rating = forms.TextInput()
    comments = forms.TextInput()

class Hike_Review_Form(forms.Form):
    user = forms.CharField(max_length=50)
    rating = forms.TextInput()
    comments = forms.TextInput()

ruff/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import *
from django.http import JsonResponse, HttpResponse
from dateutil import parser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import requests

from .models import *
import random, os, json
from django.conf import settings

media_path = settings.MEDIA_ROOT + '/'

# Main page view
def index(request):
    return render(request, 'ruff/index.html')

# View for news page
def news(request):
    return render(request, 'ruff/news.html')

#View for rendering about page
def about(request):
    return render(request, 'ruff/about.html')

'''
    All event related pages, pages with @login_required means Admin is required to login
'''
@login_required
def event_details(request):
    events = Events.get("date")
    return render(request, 'ruff/event_details.html', {"events": events})

'''
    Main event page, loads the list of events and changes the date to a UI acceptable format.
'''
def event(request):
    events = list(Events.get("name"))
    event_list = []
    for event in events:
        event.date = parser.parse(event.start_date)
        event_list.append(event)
    types = [{"value": event.type, "checked": False} for event in event_list]
    types = list({value['value']: value for value in types}.values())
    paginator = Paginator(event_list, 10)  # Show 10 events per page

    page = request.GET.get('page')
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        events = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        events = paginator.page(paginator.num_pages)
    return render(request, 'ruff/event.html', {"events": events, "selected": "name", "date_selected": "any", "event_selected": "none", "types": types})

'''
    Filter events based on date type selected.
'''
def event_date_filter(request):
    try:
        date_selected = request.POST["date_selected"] if "date_selected" in request.POST else "any"
        selected = request.POST["selected"] if "selected" in request.POST else "name"
        try:
            events = list(Events.date_filter(date_selected, selected))
        except:
            events = []
        event_list = []
        for event in events:
            event.date = parser.parse(event.start_date)
            event_list.append(event)

        types = [{"value": event.type, "checked": False} for event in event_list]
        types = list({value['value']: value for value in types}.values())

        paginator = Paginator(event_list, 10)  # Show 10 events per page

        page = request.GET.get('page')
        try:
            events = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            events = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            events = paginator.page(paginator.num_pages)
        return render(request, 'ruff/event_view.html', {"events": events, "selected": selected, "date_selected": date_selected, "types": types})
    except:
        return HttpResponse("An error occured, please try again.", status=500)

'''
    Filter events based on vaious parameters(event type, date selected and selected sorting type)
'''
def event_filter(request):
    try:
        check_list =  json.loads(request.POST["check_list"]) if "check_list" in request.POST else []
        all_checks =  json.loads(request.POST["all_checks"]) if "all_checks" in request.POST else check_list
        date_selected =  request.POST["date_selected"] if "date_selected" in request.POST else "any"
        selected =  request.POST["selected"] if "selected" in request.POST else "name"
        if(len(check_list) == 0):
            events = list(Events.get(selected))
        else:
            try:
                events = list(Events.type_filter(check_list, selected))
            except:
                events = []

        event_list = []
        for event in events:
            event.date = parser.parse(event.start_date)
            event_list.append(event)
        types = []
        for type in all_checks:
            if type in check_list:
                types.append({"value": type, "checked": True})
            else:
                types.append({"value": type, "checked": False})
        types = list({value['value']:value for value in types}.values())
        paginator = Paginator(event_list, 10)  # Show 10 events per page

        page = request.GET.get('page')
        try:
            events = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            events = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            events = paginator.page(paginator.num_pages)
        return render(request, 'ruff/event_view.html', {"events": events, "selected": selected, "date_selected": date_selected, "types": types})
    except:
        return HttpResponse("An error occured, please try again.", status=500)

'''
   Check if user's location is stored in particular session.
'''
def location_stored(request):
    user_location = request.session.get('user_location')
    if user_location != None:
        return JsonResponse({'location': True})

    return JsonResponse({'location': False})

'''
    Calculate distance between two locations
'''
def getDistance(location, park_location):
    origin = str(location["latitude"]) + "," + str(location["longitude"]) if type(location) is dict else location
    distance_km = None
    matrixurl = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=" + origin + "&destinations=" + park_location + "&key=AIzaSyDemTKrKvU6qAmvZIvC-J4JU5na3C-mGV4"
    matrixinfo = requests.post(matrixurl)
    matrixresult = json.loads(matrixinfo.text)
    if 'rows' in matrixresult.keys() and len(matrixresult['rows']) > 0:
        matrixdistance = matrixresult['rows']
        # if result is not empty
        if matrixdistance[0]['elements'][0]['status'] != 'ZERO_RESULTS':
            # get the distance
            distance = matrixdistance[0]['elements'][0]['distance']['value']
            if (distance != ""):
                distance_km = distance / 1000
    return distance_km

'''
    Main hike page, loads the list of hikes.
'''
def hike(request):
    user_location = request.session.get('user_location')
    hike_list = list(Hikes.get("name"))
    if(user_location != None):
        location = json.loads(user_location)
        return render(request, 'ruff/hike.html', {"hikes": hike_index(request, location["latitude"], location["longitude"], hike_list), "selected": "name", "diff_selected": "all", "range_distance": 10, "leash_selected": True})
    else:
        paginator = Paginator(hike_list, 10)  # Show 10 hikes per page

        page = request.GET.get('page')
        try:
            hikes = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            hikes = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            hikes = paginator.page(paginator.num_pages)
        return render(request, 'ruff/hike.html', {"hikes": hikes, "selected": "name", "diff_selected": "all", "range_distance": 10, "leash_selected": True})

'''
    get list of hikes with distanceaway away from selected location and destination location
'''
def hike_index(request, lat, lng, h_list=None):
    request.session['user_location'] = json.dumps({"latitude": lat, "longitude": lng})
    hikes_list = list(Hikes.get("name")) if h_list == None else h_list
    hike_list = []
    for hike in hikes_list:
        try:
            matrixurl = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=" + str(lat) + "," + str(lng) + "&destinations=" + hike.location + "&key=AIzaSyDemTKrKvU6qAmvZIvC-J4JU5na3C-mGV4"
            matrixinfo = requests.post(matrixurl)
            matrixresult = json.loads(matrixinfo.text)
            if 'rows' in matrixresult.keys() and len(matrixresult['rows']) > 0:
                matrixdistance = matrixresult['rows']
                # if result is not empty
                if matrixdistance[0]['elements'][0]['status'] != 'ZERO_RESULTS':
                    # get the distance
                    distance = matrixdistance[0]['elements'][0]['distance']['value']
                    if(distance != ""):
                        distance_km = distance / 1000
                        hike.distanceaway = str(round(distance_km)) + "km"
            hike_list.append(hike)
        except:
            hike_list.append(hike)
            pass

    paginator = Paginator(hikes_list, 10)  # Show 10 hikes per page
    page = request.GET.get('page')
    try:
        hikes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        hikes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        hikes = paginator.page(paginator.num_pages)
    return hikes

'''
    get list of hikes with distanceaway away from selected location and destination location
'''
def hike_location(request):
    try:
        hike_list = list(Hikes.get("name"))

        latitude = request.POST["latitude"]
        longitude = request.POST["longitude"]

        return render(request, 'ruff/hike_view.html',
                  {"hikes": hike_index(request, latitude, longitude, hike_list),
                   "selected": "name", "range_distance": 10, "leash_selected": True, "diff_selected": "all"})
    except Exception as e:
        print(e)
        return HttpResponse("An error occured, please try again.", status=500)

ruff/templates/ruff/about.html
{% extends "ruff/base.html" %}
{% block page_title %}RuffGuide{% endblock %}
{% block hike %}{% endblock %}
{% block park %}{% endblock %}
{% block restaurant %}{% endblock %}
{% block event %}active{% endblock %}
{% block content %}
    {% load static %}
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-12">About Ruff Guide.</div>
            </div>
            <br>
            <div class="row text-center">
                <div class="col-md-12">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
                    and scrambled it to make a type specimen book. It has survived not only five centuries, but also the
                    leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s
                    with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                    publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>

            </div>
        </div>

    </div>
    <br>
    <!-- /#page-content-wrapper -->

{% endblock %}

ruff/templates/ruff/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block page_title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {#    <link rel="stylesheet" href="{% static "ruff/css/flexslider.css" %}">#}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "ruff/css/fontawesome-stars.css" %}">
    <link rel="stylesheet" href="{% static "ruff/css/carousel.css" %}">
    <style>
        /*!* GLOBAL STYLES*/
        /*-------------------------------------------------- *!*/
        /*!* Padding below the footer and lighter body text *!*/
        body, html {
            height: 100%;
        }

        #container_bd {
            min-height: 100%;
        }

        body {
            padding-top: 3rem;
            color: #5a5a5a;
        }

        .carousel-control {
            padding-top: 10%;
            width: 5%;

        }

        #links {
            margin-top: -20px;
            margin-right: -150px;
            font-size: 12px;
        }

        #city {
            margin-bottom: -20px;
        }

        .background_label {
            width: 110%;
            height: auto;
            background: gray;
            border: solid gray 1px;
            padding: 10px;
            color: white;
            margin-top: 30px;
            margin-left: -20px;
            margin-bottom: -30px;
        }

        .date_label {
            background: #cccccc;
            font-size: 10px;
            font-weight: bold;
            height: 50px;
            width: 50px;
            padding: 5px;
            margin-top: -40px;
            float: right;
            color: black;
            text-align: center;
        }

        .card_image {
            padding: 20px;
            background-repeat: no-repeat;
            background-size: cover;
            margin-top: 10px;
        }

        .nav-link {

        }

        .mapSection {
            width: 100%;
            height: 100%;
            background-color: #fff;
            z-index: 0;
        }

        footer {
            background-color: #DDDDDD;
            padding-top: 10px;
            width: 100%;
        }

        .reviews {
            border: solid black 1px;
        }

        .reviews h5 {
            padding: 10px;
        }

        .reviews hr {
            margin-left: 5px;
            margin-top: -10px;
            margin-bottom: -10px;
        }

        hr {
            border: 0;
            clear: both;
            display: block;
            width: 96%;
            background-color: black;
            height: 1px;
        }

        @media only screen and (max-width: 500px) {
            .navbar-right li #links {
                margin-top: 0;
            }

            .navbar-right li #city {
                margin-bottom: 0;
            }

        }

        .hidden {
            display: none;
        }

        .unhidden {
            display: block;
        }

        .br-wrapper.br-theme-fontawesome-stars {
            display: inline-block;
        }

        .blog {
            text-decoration: none;
            color: black;
        }

        .map_view .modal {
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            overflow: hidden;
        }

        .map_view .modal-dialog {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
            max-width: 100%;
        }

        .map_view .modal-content {
            top: 35px;
            height: 100%;
            border-radius: 0;
            color: white;
            overflow: auto;
        }

        .map_view .modal-header {
            position: absolute;
            top: 0;
            right: 0;
            left: 0;
            height: 40px;
            padding: 10px;
            background: white;
            border: 0;
            z-index: 10;
        }

        .map_view .modal-title {
            font-weight: 300;
            font-size: 1em;
            color: black;
            line-height: 30px;
        }

        .map_view .modal-body {
            position: absolute;
            top: 0;
            bottom: 60px;
            width: 100%;
            height: 100%;
            font-weight: 300;
            overflow: auto;
            background: white;
            padding: 0;
        }

        .info_content {
            color: black;
        }

        #event_type ::-webkit-scrollbar {
            -webkit-appearance: none;
            width: 10px;
            background: #f1f3f5;
            border-left: 1px solid rgba(241, 243, 245, 0.3);
        }

        #event_type ::-webkit-scrollbar-thumb {
            background: rgba(135, 152, 171, 0.9);
        }


    </style>
    <!-- jQuery, Bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

    <script type="application/javascript" src="{% static 'ruff/js/jquery.cookie.js' %}"></script>
    <script src="{% static "ruff/js/jquery.barrating.min.js" %}"></script>
    <script src="{% static "ruff/js/general_map.js" %}"></script>


    {% block script %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #DDDDDD;">
    <img src="http://via.placeholder.com/140x100" style="width: 60px; height: 40px;">
    <a class="navbar-brand" href="{% url 'ruff:index' %}" style="color: black; margin-left: 5px;">Ruff Guides</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block event %}{% endblock %}">
                <a class="nav-link" href="{% url 'ruff:event' %}" style="color: black;">Events</a>
            </li>
            <li class="nav-item {% block park %}{% endblock %}">
                <a class="nav-link" href="{% url 'ruff:park' %}" style="color: black;">Parks</a>
            </li>
            <li class="nav-item {% block restaurant %}{% endblock %}">
                <a class="nav-link" href="{% url 'ruff:restaurant' %}" style="color: black;">Restaurants</a>
            </li>
            <li class="nav-item {% block hike %}{% endblock %}">
                <a class="nav-link" href="{% url 'ruff:hike' %}" style="color: black;">Hikes</a>
            </li>
        </ul>
        <div class="nav navbar-nav" style="margin-right: 20px;">
            <div class="row">
                <p id="city" style="font-size: 13px; color: black;"><a href="{% url 'ruff:about' %}">About Us</a> | <a
                        href="">Contact</a>
                </p>
            </div>
            {#            <div class="row">#}
            {#                <p id="links">Melbourne | Sydney</p>#}
            {#            </div>#}

        </div>
    </div>
</nav>
<div class="container-fluid" id="container_bd" style="margin-top: 30px">
    {% block content %}{% endblock %}
</div>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h5>About</h5>
                <p><a href="{% url 'ruff:about' %}">About Ruff Guides</a></p>
                <p><a href="#">Add your business</a></p>
                <p><a href="#">Advertise</a></p>
            </div>
            <div class="col-sm-4">
                <h5>Contact</h5>
                <p><a href="mailto:abc@ruffguides.com">abc@ruffguides.com</a></p>
            </div>
            <div class="col-sm-4 info">
                <h5>Newsletter</h5>
                <p>Sign up to our newsletter to receive updates on new exciting events and fun activities to enjoy with
                    your dog!</p>
                <p><input type='text' class="input-sm form-control" id="newsletter" value="" name="newsletter"/></p>
                <p>
                    <button type="submit" class="btn btn-success" name="newsletter-submit" id="newsletter-submit"
                            style="width: 100%">
                        Signup
                    </button>
                </p>
            </div>
        </div>
    </div>
</footer>

</body>


</html>

ruff/templates/ruff/news.html
{% extends "ruff/base.html" %}
{% block page_title %}RuffGuide{% endblock %}
{% block hike %}{% endblock %}
{% block park %}{% endblock %}
{% block restaurant %}{% endblock %}
{% block event %}active{% endblock %}
{% block content %}
    {% load static %}
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-12">
                    <h3>NEWS</h3>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-9">
                    <div class="row text-left">
                        <img src="http://via.placeholder.com/230x150" class="img-responsive">
                    </div>
                    <br>
                    <h3>News Title - ABCD adsa, asdsa</h3>
                    <p>{% lorem 10 p %}</p>
                </div>
                <div class="col-md-3">
                    <h5>Popular posts</h5>
                    <hr>
                    <div class="row" style="font-size: small">
                        <div class="col-md-3 text-center">
                            <img src="http://via.placeholder.com/140x100" class="img-responsive"
                                 style="width: 75px; height: 60px;">
                        </div>
                        <div class="col-md-9">
                            <span><a class="blog" href="{% url 'ruff:news' %}"><b>News Title</b></a> - The menu will appear collapsed on smaller
                        screens, and will appear non-collapsed on larger screens.</span>
                        </div>

                    </div>
                    <br>
                    <div class="row" style="font-size: small">
                        <div class="col-md-3 text-center">
                            <img src="http://via.placeholder.com/140x100" class="img-responsive"
                                 style="width: 75px; height: 60px;">
                        </div>
                        <div class="col-md-9">
                                <span><a class="blog" href="{% url 'ruff:news' %}"><b>News Title</b></a> - The menu will appear collapsed on smaller
                        screens, and will appear non-collapsed on larger screens.</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
    <br>
    <!-- /#page-content-wrapper -->

{% endblock %}